### ISSUE TITLE
Pin numpy<2.0.0 to omit "ValueError: numpy.dtype size changed, may indicate binary incompatibiliy"

### ISSUE THREAD

**Issue by mwip** [kraina-ai/quackosm#145]
A current install results in the following error:

```bash
mamba create -n quackosm pip python=3.11
mamba activate quackosm
pip install quackosm"[cli]"
quackosm germany-240701.osm.pbf
Traceback (most recent call last):
  File "/home/username/mambaforge/envs/quackosm/bin/quackosm", line 5, in <module>
    from quackosm.__main__ import main
  File "/home/usernamemambaforge/envs/quackosm/lib/python3.11/site-packages/quackosm/__init__.py", line 8, in <module>
    from quackosm.functions import (
  File "/home/username/mambaforge/envs/quackosm/lib/python3.11/site-packages/quackosm/functions.py", line 18, in <module>
    from quackosm.pbf_file_reader import PbfFileReader
  File "/home/username/mambaforge/envs/quackosm/lib/python3.11/site-packages/quackosm/pbf_file_reader.py", line 34, in <module>
    from pyarrow_ops import drop_duplicates
  File "/home/username/mambaforge/envs/quackosm/lib/python3.11/site-packages/pyarrow_ops/__init__.py", line 4, in <module>
    from pyarrow_ops.join import join
  File "/home/username/mambaforge/envs/quackosm/lib/python3.11/site-packages/pyarrow_ops/join.py", line 5, in <module>
    from cjoin import inner_join
  File "pyarrow_ops/cjoin.pyx", line 1, in init cjoin
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

This is caused by a `numpy>2.0.0` regression and can be mitigated by downgrading `numpy`

```bash
pip install "numpy<2.0.0" --force-reinstall
```

A possible solution would be to pin `numpy` in the `pyproject.toml`

```diff
  [project]
  name = "QuackOSM"
  ...
  dependencies = [
      ...
+     "numpy<2.0.0",
  ]
```

See also [this stackoverflow question](https://stackoverflow.com/a/78641304/3250126)

**Comment by RaczeQ** [comment]
Hi @mwip, thank you for raising this issue.
I can confirm that I've also stumbled across this error during development. The original issue comes from the fact that one of the dependencies, `pyarrow-ops` is compiled during installation and is using `numpy` binaries. After updating the `numpy` without reinstalling `pyarrow-ops`, is results in this binary incompatibility. Probably during installation, `pyarrow-ops` compiled with older version of numpy that was preinstalled with mamba environment and then was updated because of other dependencies minimal requirement.

Since I'm only using a small portion of this dependency, I'll reimplement it in `QuackOSM` and leave numpy unbounded, so it'll work properly both in 1.x.x and 2.x.x version of `numpy`.
